apiVersion: 1

datasources:
  - name: ReportD
    type: yesoreyeram-infinity-datasource
    uid: reportd
    access: proxy
    url: http://reportd:8080
    isDefault: false
    editable: true
    jsonData:
      auth_method: bearerToken
      allowedHosts:
        - http://reportd:8080
      httpHeaderName1: Authorization
    secureJsonData:
      bearerToken: $__env{REPORT_TOKEN}
      httpHeaderValue1: Bearer $__env{REPORT_TOKEN}
