apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: $__env{READONLY_USER}
    secureJsonData:
      password: $__env{READONLY_PASSWORD}
    jsonData:
      database: timesync
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
